mozilla-frontend-infra/firefox-performance-dashboards

- src/App/index.jsx
- src/App/metricsGraphics.css
- src/components/Header/index.jsx
- src/config.js
- src/views/Benchmark/index.jsx
This PR enhanches the configuration file with these features:
* Support having different sets of benchmarks per platform
* Define default labels for graphs + method to override per benchmark
* Define default colors for graphs + method to override per benchmark
> New config: labels and colors + differentiate platforms

- netlify.toml
We added routing for the app bb3ba3f38c40242fa15c21fce5fcfe16f178687e,
however, it only works locally because we did not configure Netlify to
do the same.
> Issue #30 - Netlify not routing properly

- package.json
- src/App/index.jsx
- src/App/metricsGraphics.css
- src/utils/prepareData.js
- src/views/Benchmark/index.jsx
- yarn.lock
It has a lot of features that metrics-graphics does not have at the moment.
chart.js is a more popular charting tool, thus, I expected more features being available
in it.
This cuts development cost to fix some of the other issues already filed for our dashboard.
> Issue #40 - Switch to react-chartjs-2 from react-metrics-graphics

- src/config.js
- src/utils/prepareData.js
- test/mocks/linux64/preparedData.json
This change affects the following benchmarks:
Execution time -> Score:
* MotionMark Animometer
* MotionMark HtmlSuite
* StyleBench
Score -> Execution time
* Web Tooling (JS shell)
> Issue #60 - Calculate Y labels on lower_is_better value from Treeherder

- package.json
- yarn.lock
There was an issue in the publishing of the previous version.
> Upgrade to version 2.0.1 of perf-goggles

- .gitignore
- package.json
- src/components/Graphs/index.jsx
- src/components/Loading/index.jsx
- src/components/Navigation/index.jsx
- yarn.lock
This PR adds code splitting  using import() and react-loadable to take advantage of webpack code splitting to reduce build size.
> reduce build size with code splitting

- package.json
- src/utils/fetchData.js
- yarn.lock
This is simply to keep in sync with Firefox Health upgrading versions.
> Use new version of perf-goggles

- src/utils/fetchData.js
Certain Treeherder API requests can trigger a 503 and that
gets the app into an eternal "loading" state.
> Do not let failed fetch requests to propagate

- src/config.js
Also prevent platforms from being tra…nsformed to end with -shippable-shippable. I think we need to move to all '-shippable' platforms and remove the `platformTransformations` code, but we can take care of that later.
Fixes #168
> Add Chromium comparisons for Tp6

- src/config.js
- test/config.test.js
Fixes issue #202
This is a fallout from https://github.com/mozilla-frontend-infra/firefox-performance-dashboard/pull/198
The overview page would look fine, however, the drilldown would only show one platform:
After the fix we can see all configurations:
> Fix: show all configurations in the drilldown page

- src/awfy.js
- test/config.test.js
This introduces browsertime results. For now I've added the Fenix speedometer results and cold page load for Amazon. There will need to be further tweaks as we roll out browsertime to more of our mobile tests, but we'll also be blocked on #290 to show results from the fenix branch. This patch shows the results running on mozilla-central.
> Add browsertime speedometer results and cold page load for Amazon

- test/recordings/Perfherder_169537080/Linux64_2717411455/Kraken-no-subtests-_2260542550/recording.har
- test/recordings/Perfherder_169537080/Windows-10_2105768759/Tp5o-opt-no-subtests-_3522863577/recording.har
- test/recordings/Perfherder_169537080/Windows-10_2105768759/sessionrestore_1993046815/recording.har
A recordings refresh.
The recordings were out of date (the request recorded before did not have `no_retriggers=true`)
The changes were generated automatically by running `yarn test`
> Refresh polly recordings

- src/awfy.js
@airimovici when trying to push this I had test failures:
```
husky > pre-push (node v15.4.0)
$ jest
PASS  test/chartJs.test.js
PASS  test/config.test.js
PASS  test/fetchAndCache.test.js
PASS  test/fetchWrapper.test.js
PASS  test/components/Pickers.test.jsx
FAIL  test/perfherder.test.js (11.241s)
● Perfherder › Windows 10 › Tp5o opt (no subtests)
: Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Error:
77 |     };
78 |
> 79 |     it('Tp5o opt (no subtests)', async () => {
|     ^
80 |       seriesConfig.suite = 'tp5o';
81 |
82 |       const data = await queryPerformanceData(seriesConfig, { timeRange: TIMERANGE });
at new Spec …
```
> Switch to results without conditioned profiles and show GeckoView WebRender

- src/awfy.js
acreskey noticed that we're missing Fenix data, which was caused by the disabling of conditioned profiles.
> Stop using conditioned profiles for Fenix page load tests

- src/awfy.js
I don't think we need to wait for the bug to be resolved, let's remove the results for the redesign and the remaining chart will show these results once the patch lands.
> Bug 1699764 - Remove Facebook page load test using legacy design

- src/awfy.js
We only have firefox `cnn-ampstories` live results on raptor and with series name like `raptor-tp6-cnn-ampstories-firefox-cold`
https://treeherder.mozilla.org/perfherder/graphs?highlightAlerts=1&series=mozilla-central,2851268,1,10&series=mozilla-central,2852642,1,10&series=mozilla-central,2695035,1,10&series=mozilla-central,2695045,1,10&timerange=1209600
I assumed the suite names will be consistent with the mobile like: `amazon-search` , `microsoft-support`, `bbc`.
> Add desktop live sites

- src/awfy.js
I don't think we should merge this, but it's going to be useful to see the webext and browsertime benchmark results on the deploy previews whilst we're migrating them.
> Temporarily show both webext and browsertime benchmark results during migration

- src/awfy.js
- test/config.test.js
A couple of bugs recently resolved caused the signatures we care about to change. The Android tests now use the -qr WebRender platforms, and we've dropped the use of 'nocondprof'. Let's hold off merging this until we have accumulated some of the new signatures, but feel free to review.
> Android WebRender platforms and nocondprof removal

- src/awfy.js
These tests should run for the first time on Saturday 17th July. We should hold off merging until we can confirm results are shown in the deploy preview.
> Add Samsung Galaxy S7 to mobile platforms

- src/awfy.js
Google Docs is going to be switching to a canvas-based rendering. This PR adds the page load test for the canvas preview to the AWFY site list
> Add google docs canvas preview to warm page load site list

- src/awfy.js
I noticed we aren't showing the JetStream 2 results.
> Add JetStream 2 benchmark results

- src/awfy.js
Removing Google Pixel 2 from AWFY as part of FXP-2435
> FXP-2435 Disable P2 perf tests

- src/awfy.js
Currently the AWFY graphs for Fenix nofis are using firefox-android data.
This patch make sure we use mozilla-central and autoland
> Bug-1893971-fix-awfy-graph-post-monorepo

- src/awfy.js
For https://bugzilla.mozilla.org/show_bug.cgi?id=1904980
Looks as expected to me? 
(and I just realized you can see it yourself in the deploy preview too)
> Add Win 11 platform to AWFY

- src/awfy.js
closes #520 
closes #517
There seems to be a bug where I can't remove motion mark 1.0 (e.g. #519) without the dashboard going completely blank
so for the time being we can just keep motionmark 1.0 and 1.3?
> Add motionmark 1.3, update landing path, remove osx 10.14
