package.json, src/components/Header/index.jsx, src/components/Header/style.css, src/config.js, src/views/Benchmark/index.jsx, test/views/__snapshots__/Benchmark.test.jsx.snap, yarn.lock
This allow us to select various AWFY platforms/benchmarks running on Treeherder.
=> Initial MVP layout - Fetch and plot AWFY subbenchmarks

package.json, src/App/index.jsx, src/App/metricsGraphics.css, src/config.js, src/utils/prepareData.js, src/views/Benchmark/benchmark.css, src/views/Benchmark/index.jsx, test/views/__snapshots__/Benchmark.test.jsx.snap
Besides showing Chrome data there's some polishing of the links for Perfherder.
=> Issue #6 - Overlay Chrome data

package.json, src/components/Graphs/index.jsx, yarn.lock
- Removed “Perfherder link” text 
- Added Material UI link icon using **materialui** node package next to benchmark title
=> Issue #68 - Add icons for Perferherder links

package.json, src/components/Graphs/index.jsx, src/utils/fetchData.js, src/utils/prepareData.js, test/mocks/linux64/fetchedData.json, test/mocks/linux64/preparedData.json, yarn.lock
This version of perf-goggles unifies the entry point to the library and it works for both this project as well as fx-health-dashboard.
=> Upgrade to perf-goggles v2

.eslintrc.js, .neutrinorc.js, jest.config.js, package.json, src/App/index.jsx, src/components/ChartJSWrapper/index.jsx, src/components/Graphs/index.jsx, src/components/Legend/index.jsx, src/components/Navigation/index.jsx, src/components/Pickers/index.jsx, src/index.jsx, src/utils/prepareData.js, src/utils/validCombination.js, src/views/Benchmark/index.jsx, test/components/__snapshots__/Pickers.test.jsx.snap, webpack.config.js, yarn.lock
I think something has changed on Travis recently since this project also started timing out its Travis builds.
=> Upgrade to Neutrino 9 beta

src/components/Graphs/index.jsx
Fix for #101 
I added default numDays=90 and it is working as expected. Changing time range from picker is also working fine. 
@armenzg  Please review and let me know if this is fine or not?
=>  Issue #101 - Fix drilldown links

src/utils/prepareData.js, test/mocks/linux64/preparedData.json
=> Issue #96 - Fix graph y range on mobile

src/config.js
=> Add Tp6 CNN and rename existing to Tp6 CNN AMP Stories

src/config.js
=> Add Tp6 Netflix and Tp6 Twitch

src/config.js, test/mocks/linux64/fetchedData.json, test/mocks/linux64/preparedData.json
=> Add ARES6 benchmark for Firefox and Chrome

src/config.js
=> Replace Tp6 Wikia with Tp6 Fandom

src/components/ChartJSWrapper/index.jsx
Closes https://github.com/mozilla-frontend-infra/firefox-performance-dashboard/issues/177
=> Fix charts resizing unnecessarily

src/utils/fetchAndCache.js, src/utils/perfherder.js, test/fetchAndCache.test.js
Lets see how this works out :smile:
=> Cache requests using Cache API

.travis.yml, netlify.toml, package.json
This is unify the versions used across local development, Travis CI and Netlify deployments.
=> Specify Yarn/Node version

package.json, src/index.jsx, yarn.lock
Here is the snapshot of my sentry account that reflects `err` is succesfully went to sentry dashboard.
=> Added support for sentry.

.renovaterc, .renovaterc.md, renovate.json
* Automerge patch releases
* Disable minor updates
* Set Monday schedule
=> Reconfigure Renovate

src/awfy.js, test/config.test.js
=> Switch to shippable platform configurations

src/awfy.js
=> Split Android platforms by device

src/utils/perfherder.js, test/perfherder.test.js
https://github.com/mozilla-frontend-infra/firefox-performance-dashboards/issues/305
=> Issue 305 - No data because of faulty signature call

src/utils/fetchAndCache.js, src/utils/fetchWrapper.js, test/fetchAndCache.test.js, test/fetchWrapper.test.js
Ref: https://github.com/mozilla-frontend-infra/firefox-performance-dashboards/issues/334
=> fetch wrapper to elimitate duplicate requests

src/awfy.js, src/config.js, src/h3.js
@ddragana this adds the http3 results to the main arewefastyet.com under a new 'Network' category and means we would no longer need to maintain the http3 branch and branch deployment.
=> Add http3 results to new network category

src/awfy.js, test/config.test.js
See https://bugzilla.mozilla.org/show_bug.cgi?id=1675836
=> Remove cranelift configurations

src/components/App/index.jsx, src/components/Description/index.jsx
https://github.com/mozilla-frontend-infra/firefox-performance-dashboards/issues/341
=> Issue 341 - Add page descriptions

src/awfy.js, test/config.test.js
=> Bug 1663449 - Stop using conditioned profiles for remaining Firefox tests running in Raptor

src/awfy.js
I missed the page load tests in #360
=> Bug 1663449 - Stop using conditioned profiles for Raptor page load tests

src/awfy.js
Demonstration of showing visual metrics for page load (where available).
=> Switch page load results to show visual metrics

src/awfy.js, src/components/App/index.jsx, src/components/PerfherderGraph/index.jsx
=> Show additional results from Talos 

src/components/PerfherderGraph/index.jsx, src/utils/chartJs.js, test/chartJs.test.js
@airimovici this seems to work for me, but perhaps you could suggest improvements?
=> Show full date range instead of limiting to available data

src/awfy.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1670005
=> Remove Fennec from applications under test

src/awfy.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1706173
=> Restore macOS 10.14 as a separate platform entry

src/awfy.js
FXP-2384 Display "Fenix-Fission" and "GeckoView-Fission" perf tests on AWFY
=> Make AWFY display fission and non-fission variants for Geckoview and Fenix tests

src/awfy.js
=> Change 'Speedometer' label to 'Speedometer 2'

README.md, src/awfy.js
=> Add M2 machines to AWFY

webpack.config.js
=> fix webpack config

src/awfy.js
=> Add new windows naming
